/**
 * TeamspeakAnalytics - REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface GetClientDetailedInfo {
  channelId?: number;
  uniqueIdentifier?: string;
  nickName?: string;
  serverQueryName?: string;
  databaseId?: number;
  type?: ClientType;
  version?: string;
  connectionIp?: string;
  plattform?: string;
  description?: string;
  inputMuted?: boolean;
  outputMuted?: boolean;
  outputOnlyMuted?: boolean;
  isRecording?: boolean;
  serverGroupIds?: Array<number>;
  channelGroupsIds?: Array<number>;
  created?: Date;
  lastConnected?: Date;
  totalConnectionCount?: number;
  away?: boolean;
  awayMessage?: string;
  connectionTime?: string;
  idleTime?: string;
}

export enum ClientType {
  NUMBER_0 = 0,
  NUMBER_1 = 1
}
