/**
 * TeamspeakAnalytics - REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface GetChannelListInfo {
  id?: number;
  parentChannelId?: number;
  order?: number;
  name?: string;
  topic?: string;
  isDefaultChannel?: boolean;
  hasPassword?: boolean;
  isPermanent?: boolean;
  isSemiPermanent?: boolean;
  codec?: Codec;
  codecQuality?: number;
  neededTalkPower?: number;
  iconId?: number;
  durationEmpty?: string;
  totalFamilyClients?: number;
  maxClients?: number;
  maxFamilyClients?: number;
  totalClients?: number;
  neededSubscribePower?: number;
}

export enum Codec {
  NUMBER_0 = 0,
  NUMBER_1 = 1,
  NUMBER_2 = 2,
  NUMBER_3 = 3,
  NUMBER_4 = 4,
  NUMBER_5 = 5
}
