/**
 * TeamspeakAnalytics - REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface GetServerListInfo {
  id?: number;
  port?: number;
  status?: string;
  clientsOnline?: number;
  queriesOnline?: number;
  maxClients?: number;
  uptime?: string;
  name?: string;
  autostart?: boolean;
  machineId?: string;
  uid?: string;
}
