name: NPM CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build-npm:
    name: Build WebApp
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Angular
      run: npm install -g @angular/cli
    - name: Install NPM packages
      run: npm install
    - name: Build the WebApp
      run: ng build --prod
